### ISSUE TITLE
Compare page US-6

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#12]
## Value proposition

As a User
I want to Add cars to compare List
in order to compare cars

## Description

![6](https://github.com/maksymvasylyev/capstone-project/assets/102429024/f0d5aad0-a5cc-415c-9c3a-3ec7350af361)

## Acceptance criteria

- [x] Compare buttons are added to all cars cards from the favorite page
- [x] By clicking Compare button - car is moving to the Compare page and button is toggled with colors
- [x] If nothing is added to compare - Empty Screen shows text
- [x] Button on the bottom "Compare other" deletes the list and brings us to Favorite page
- [x] Links to Home page, to Favorite Page and to Compare Page are displayed at the bottom of each page, except start page
- [x] on page 2 - two pictures of compared cars are displayed in the row, than full information of both with common title

## Tasks

- [x] Create new branch Compare
- [x] Create Compare component
- [x] Add filtered array to Compare component
- [x] Create page CompareList
- [x] Add Compare buttons to cards on Favorite Page
- [x] Create Links to Home Page, to Favorite Page and to Compare Page
