### ISSUE TITLE
AddCarForm US-7

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#15]
## Value proposition

As a User
I want to See a Form
in order to enter Data

## Description
![7](https://github.com/maksymvasylyev/capstone-project/assets/102429024/41d10c56-6e00-4743-96e0-61af6ccae4c0)

## Acceptance criteria

- [ ] Title is shown on the top
- [ ] Form has options and input fields
- [ ] Submit button is under the Form fields
- [ ] Link to Add Car Form is always displayed 
in the bottom

## Tasks

- [ ] Create new branch "AddCarForm"
- [ ] Pages/addCar
- [ ] Components/AddCarForm
- [ ] Create form
- [ ] Set all fields as "required"
- [ ] Create Submit button
