### ISSUE TITLE
Add car US-8

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#16]
## Value proposition

As a User
I want to Use Add button
in order to Add new car

## Description

![8](https://github.com/maksymvasylyev/capstone-project/assets/102429024/01654be2-9059-44d1-9e30-fc347c19bc49)

## Acceptance criteria

- [x] Title is shown on the top
- [x] User full fill all form fields that he knows and click "add car" button
- [x] After confirm button is pressed - user stays on the same page and see new car displayed with full information.
- [x] Picture of the car is displayed one in array
- [x] Description is under the picture: each point in the new line
- [x] NewCarForm is always visible
- [x] NewCarForm data is reset, but not focused.
- [x] User can enter new car.
- [x] Every new car is a part of my car data, but displayed only on "MyGarage" page

## Tasks

- [x] Create new branch "AddNewCar"
- [x]  Components/AddNewCar
- [x] Make "Add car" functionality

**Comment by mbosselmann** [comment]
Hi Max,
good job! But I have some remarks for you to consider:
- you should describe in your acceptance criteria which information the user needs to give
- you could also describe which information are required
- describe what will happen after submitting the form (will the user stay on the page in order to enter a new car or will he be redirected? will the form data be resetted?)
I hope this does help :)

**Comment by Leukipos** [comment]
Hello Max,
This looks got to me. Here we go!
cheers LX
