### ISSUE TITLE
Edit Car US-9

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#17]
## Value proposition

As a User
I want to See Edit button
in order to Edit my car

## Description

![9](https://github.com/maksymvasylyev/capstone-project/assets/102429024/b559284e-537b-4cbd-b73c-101d26362771)

## Acceptance criteria

- [ ] New Car with full information is displayed
- [ ] Edit button is displayed

## Tasks

- [ ] Create new branch "EditCar"
- [ ] Make "Edit car" functionality

**Comment by Leukipos** [comment]
LGTM
