### ISSUE TITLE
Delete Car US-10

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#18]
## Value proposition

As a User
I want to See delete button
in order to Delete my Car

## Description

![10](https://github.com/maksymvasylyev/capstone-project/assets/102429024/a3a8b17b-f3a9-4389-9afc-2b022029cc2f)

## Acceptance criteria

- [x] New Car with full information is displayed
- [x] Card has Edit and delete buttons
- [x] After pressing "Delete button" - car is deleted immidiatelly 
- [x] "Add to compare list" button is displayed 
under the car

## Tasks

- [x] Create new branch "DeleteCar"
- [x] Make "Delete car" functionality
- [x] Add "Compare" button
