### ISSUE TITLE
Filter Form

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#2]
## Value proposition

As a User
I want to See the Filter Form
in order to interact with it

## Description

![2](https://user-images.githubusercontent.com/102429024/236136054-d9baf430-0cd4-46ec-8554-c484c1cbbf5f.png)

## Acceptance criteria

- [x] Title is shown on the top
- [x] Form has 4 "options" fields
- [x] Submit button is under the Form fields
- [x] Link to FilterForm is added to page 1 and 
always displayed while scrolling

## Tasks

- [x] Create new branch "FilterForm"
- [x] Pages/FilterForm
- [x] Components/FilterForm
- [x] Create form with 4 "option" inputs
- [x] Set all fields as "required"
- [x] Create Submit button
- [x] Edit page 1 to see the link to FilterForm

**Comment by CJAkkuec** [comment]
> As a User
> I want to See the Form
> in order to Filter

I'd probably suggest to put emphasis on the interaction with the filter form, instead of "seeing" it. Looking good otherwise.

**Comment by maksymvasylyev** [comment]
Hi! thank you for your review. Your tips are very useful and help to make better planning.
I have followed your advices.
