### ISSUE TITLE
AddNewCarPicture US-11

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#21]
## Value proposition

As a User
I want to Add picture of My Car
in order to See the picture of my car in added Cars, instead of default picture

## Description

![11](https://github.com/maksymvasylyev/capstone-project/assets/102429024/9c2345d1-e18c-44ea-9c92-a129925afeef)

## Acceptance criteria

- [ ] input to add a picture with "Add picture" button are displayed bellow all form fields
- [ ] By clicking "Add button" - user can choose a picture of his car from his computer (Handy)
- [ ] After clicking "Go" button - picture of his car is displayed above car description (instead of default picture)

## Tasks

- [ ] Create new branch "AddNewCarPicture"
- [ ] Connect Cloudinary to the project
- [ ] Make functionality to upload picture to cloudinary
- [ ] Make functionality to get picture from cloudinary

**Comment by maksymvasylyev** [comment]
Sorry for my "Task List", but I don`t even imagine steps that I will need to make.

**Comment by MerleMak** [comment]
Hi Max, 
No worries about the tasks list :D 
I recommend you to add some steps when you finished the cloudinary workshop, as it will help you to structure your workday :)
