### ISSUE TITLE
Add DataBase to BackEnd US-12

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#22]
## Value proposition

As a User
I want to See a list of all cars from BackEnd
in order to See list of cars as before

## Description

![12](https://github.com/maksymvasylyev/capstone-project/assets/102429024/ecb372d6-7b0e-4d9b-bf1e-66830d0ea5d8)

## Acceptance criteria

- [ ] DataBase is displayed from BackEnd

## Tasks

- [ ] Create branch BackEnd
- [ ] Add DataBase to MongoDB Atlas
- [ ] Connect MongoDB Atlas DataBase to the Project
