### ISSUE TITLE
Styling US-13

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#23]
## Value proposition

As a User
I want to See good organised App that looks well
in order to Use App with pleasure and no difficulties

## Description

![13](https://github.com/maksymvasylyev/capstone-project/assets/102429024/b02f00cf-2580-4763-9535-4b9ea26e5c25)

## Acceptance criteria

- [ ] All pages are styled
- [ ] All components are organised to be used with no difficulties and misunderstandings

## Tasks

- [ ] Create new branch "Styling"
- [ ] Style all elements to be beautiful and understandable

**Comment by HenrikeStahlhut** [comment]
LGTM 👍🏻
