### ISSUE TITLE
Dark Mode-US14

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#33]
## Value proposition

As a User
I want to See another styling of the App
in order to Choose which one I like better

## Description
![14](https://github.com/maksymvasylyev/capstone-project/assets/102429024/c304fe82-8f86-4fbd-b93b-6d1b12094e26)

## Acceptance criteria

- [ ] Colours of main elements are changed on each page
- [ ] Toggle mode button is displayed on the top of each page

## Tasks

- [ ] Create new branch
- [ ] Change primary, background, text and other colours in Global style 
depending on Dark Mode state.
