### ISSUE TITLE
Result of Formular search

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#4]
## Value proposition

As a user
I want to be able to search the car list according to certain criteria
in order to find a car for me that meets these criteria

## Description

![3](https://user-images.githubusercontent.com/102429024/236239823-6dc90083-311c-4860-bcc1-105422508673.png)

## Acceptance criteria

- [x] By clicking "Submit" button - Filtered Cards of cars are displayed 2 in a row
- [x] Each card has price on it
- [x] Name and model are displayed under each card
- [x] If nothing found - text is shown

## Tasks

- [x] Create new branch "FilterCars List"
- [x] Create FilteredCarsList component
- [x] Add OnSubmit function to Form in Form component
- [x] Add filtered array to FilteredCards component
- [x] Display IMG and price of each card
- [x] If no search result - display text
- [x] Add to Form Page

**Comment by maksymvasylyev** [comment]
Thank you very much!

**Comment by maksymvasylyev** [comment]
Done
