### ISSUE TITLE
Car Details

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#5]
## Value proposition

As a User 
I want to see details of the car
in order to know more about this car

## Description

![4](https://user-images.githubusercontent.com/102429024/236398033-172635a2-d65e-43f3-97a0-cefb7127152c.png)

## Acceptance criteria

- [x] CarDetailsCard of car is displayed big
- [x] Under the card there is a full description
- [x] On the top "Return to search result" Link

## Tasks

- [x] Create new branch DetailsCar
- [x] Create DetailsCard component - [id].js
- [x] Add full description to [id].js
- [x] Add "Return to search result" link

**Comment by CJAkkuec** [comment]
Everything's looking good, just two minorthings:

> DetailsCard of car is displayed big

I'd probably suggest a more descriptive name, such as CarDetailsCard, because it is a details card for a car. I want to be able to find what I'm looking for with just a quick glance. 👁️ 👄 👁️ ✨ 

> Add "Return to search result" link
Hint: Make sure to give some thought to how the search process is supposed to work, and at what point (and how) the user should be able to reset their search results. I think returning to the search results from the details page is a very good idea, but at some point (maybe not as part of the user story), the user should have a convenient way to clear their search results.

**Comment by maksymvasylyev** [comment]
Thank you very much for your tips. You are write about first paragraph - it will be much clearly.
About clear search result - I will add navigation to home page with new FilterForm in next User Stories.
Thanks again for your time by reviewing.

**Comment by mbosselmann** [comment]
Hi Max,
LGTM! 🦊
