### ISSUE TITLE
Favorite page US-5

### ISSUE THREAD

**Issue by maksymvasylyev** [maksymvasylyev/capstone-project#7]
## Value proposition

As a User 
I want to Add cars to favorite
in order to see my favorite cars

## Description

![5](https://user-images.githubusercontent.com/102429024/236479811-ebd91693-df26-4fcf-b2cc-a861787d6749.png)

## Acceptance criteria

- [x] like icons are added to all cars pictures on all pages, except starting page
- [x] By clicking Like button - car is moving to the favorite page
- [x] If nothing is liked - Empty Screen shows text
- [x] On Screen 2: if Like button is clicked - icon changes immediately and card is removed from favorite list after reload
- [x] Link to home page is displayed at the bottom

## Tasks

- [x] Create new branch Favorite
- [x] Create Favourite component
- [x] Add filtered array to Favourite component
- [x] Create page Favourite
- [x] Add favorite button to cards
- [x] Create Link to Home Page

**Comment by HenrikeStahlhut** [comment]
LGTM 🕺

**Comment by maksymvasylyev** [comment]
Done
